Areas/Admin/Controllers/BookAppointmentController.cs
using MyOnlineClinic.Entity;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Web.Controllers;
using MyOnlineClinic.Web.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web.Mvc;
using MyOnlineClinic.Web.Helper;
using System.Data.SqlClient;
using MyOnlineClinic.Migrator;
using System.Globalization;

namespace MyOnlineClinic.Web.Areas.Admin.Controllers
{
    public class BookAppointmentController : BaseController
    {
        private readonly IAppointmentService appointmentService = null;
        private readonly IDoctorService doctorService = null;
        private readonly IUserService userService = null;
        protected readonly IUserService UserService;
        private readonly IOrganizationService _organiztionService;
        private readonly IClinicService _clinicService;
        private readonly ILoginHelper _loginHelper;
        private readonly ICountryService _countryService;
        private readonly ICityService _cityService;
        private readonly ILookUpModuleService _moduleService;
        private readonly IPermissionsService _permissionService;
        private readonly ILookUpUserRolesService _roleService;
        private readonly IPermissionInModuleService _permissioninmoduleService;
        private readonly IAdminUserService _adminuserService;
        private readonly ITimeZoneService _timeZoneService;
        private readonly ITitleService _TitleServices;
        private readonly IGenderService _genderService;
        private readonly IStateService _stateService;
        private readonly IUregisteredOrganizationService _unregisteredOrganizationService;
        IProfessionTypeService _professiontypeservice;
        IPaymentHelper _paymentService;
        private readonly IPatientService _patientServices;
        private readonly IUnregisteredClinicService _unregisteredClinicService;
        private readonly IPaymentService _servicePayment;
        private readonly IVoucherService _voucherService;

        public BookAppointmentController(IAppointmentService appointmentService, IDoctorService doctorService, IUserService userService, IOrganizationService organiztionService, IClinicService clinicService,
        ICountryService countryService, ICityService cityService, ILookUpModuleService moduleService,
          IPermissionsService permissionService, ILookUpUserRolesService roleService,
          IPermissionInModuleService permissioninmoduleService, IAdminUserService adminuserService, ITimeZoneService timezoneService, ITitleService TitleServices, IGenderService genderService, IStateService stateService, ILoginHelper loginHelper, IUregisteredOrganizationService unregisteredOrganizationService

          , IProfessionTypeService professiontypeservice, IPaymentHelper paymentService, IPatientService patientServices, IPaymentService servicePayment, IUnregisteredClinicService unregisteredClinicService, IVoucherService voucherService)
        {
            this.appointmentService = appointmentService;
            this.doctorService = doctorService;
            this.userService = userService;
            UserService = userService;
            _organiztionService = organiztionService;
            _clinicService = clinicService;
            _loginHelper = loginHelper;
            _countryService = countryService;
            _cityService = cityService;
            _moduleService = moduleService;
            _permissionService = permissionService;
            _roleService = roleService;
            _permissioninmoduleService = permissioninmoduleService;
            _adminuserService = adminuserService;
            _timeZoneService = timezoneService;
            _TitleServices = TitleServices;
            _genderService = genderService;
            _stateService = stateService;
            _unregisteredOrganizationService = unregisteredOrganizationService;
            _professiontypeservice = professiontypeservice;
            _paymentService = paymentService;
            _patientServices = patientServices;
            _servicePayment = servicePayment;
            _unregisteredClinicService = unregisteredClinicService;
            _voucherService = voucherService;
        }


        public ActionResult Index(int id)
        {
            var Loginid = userService.GetPatientById(id).FirstOrDefault().LoginId;

            ReadOnlyCollection<TimeZoneInfo> tz;
            tz = TimeZoneInfo.GetSystemTimeZones();
            var timeZoneList = tz.Select(p => new SelectListItem { Value = p.Id, Text = p.DisplayName }).ToList();
            ViewBag.Timezone = timeZoneList;
            SearchViewModel model = new SearchViewModel();
            var Cmodel = UserService.GetLoginPatientById(Loginid).Select(x => new SearchViewModel
            {
                PatientId = x.LoginId,
                org = x.OrgId,
                Timezone = x.TimeZoneString,
                MemberId = x.MemberId,
                PatientLoginId = x.LoginId

            }).FirstOrDefault();
            var Omodel = _organiztionService.GetOrganizationById(Cmodel.org);
            var ClinicDecrypt = _clinicService.GetClinicsListbyOrgid(Cmodel.org, Omodel.OrganizationType).ToList();
            for (int i = 0; i < ClinicDecrypt.Count; i++)
            {
                ClinicDecrypt[i].ClinicName = StringCipher.Decrypt(ClinicDecrypt[i].ClinicName);
            }
            model.ClinicList = ClinicDecrypt;
            model.PatientLoginId = Cmodel.PatientLoginId;
            model.MemberId = Cmodel.MemberId;
            BindType(model);
            return View(model);
        }

        public SearchViewModel BindType(SearchViewModel model)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            List<SelectListItem> Prof = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = AppointmentType.VideoConsult.ToString(), Value = ((int)AppointmentType.VideoConsult).ToString() });
            items.Add(new SelectListItem { Text = AppointmentType.HomeVisit.ToString(), Value = ((int)AppointmentType.HomeVisit).ToString() });
            items.Add(new SelectListItem { Text = AppointmentType.ClinicVisit.ToString(), Value = ((int)AppointmentType.ClinicVisit).ToString() });
            Prof.Add(new SelectListItem { Text = Profession.Clinic.ToString(), Value = ((int)Profession.Clinic).ToString() });
            Prof.Add(new SelectListItem { Text = Profession.GP.ToString(), Value = ((int)Profession.GP).ToString() });
            Prof.Add(new SelectListItem { Text = Profession.Allied_Health.ToString(), Value = ((int)Profession.Allied_Health).ToString() });
            Prof.Add(new SelectListItem { Text = Profession.Specialist.ToString(), Value = ((int)Profession.Specialist).ToString() });
            model.AppointmentTypeList = items;
            model.ProfessionList = Prof;
            model.CountryList = _countryService.GetCountryList().Select(x => new LookUpCountry { CountryId = x.CountryId, CountryName = StringCipher.Decrypt(x.CountryName) }).ToList();
            var CityList = model.MemberId > 0 ? _cityService.GetCityList() : new List<LookUpCity>();
            for (int i = 0; i < CityList.Count; i++)
            {
                CityList[i].LookUpCityName = StringCipher.Decrypt(CityList[i].LookUpCityName);
            }
            model.CityList = CityList;

            var Statelist = model.MemberId > 0 ? _stateService.GetStateList() : new List<LookUpState>();
            for (int i = 0; i < Statelist.Count; i++)
            {
                Statelist[i].StateName = StringCipher.Decrypt(Statelist[i].StateName);
            }
            model.StateList = Statelist;
            model.ProfessionTypes = _professiontypeservice.GetProfessionTypesList().Select(x => new ProfessionTypes { Id = x.Id, ProfessionName = StringCipher.Decrypt(x.ProfessionName) }).ToList();
            model.ProfessionSubList = _professiontypeservice.GetProfessionSubTypesList();

            return model;

        }
        public ActionResult GetProfessionSubTypes(int Id)
        {
            var ProfessionSubType = _professiontypeservice.GetProfessionSubTypesList().Where(t => t.Id == Id).ToList();
            return Json(ProfessionSubType, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search(SearchViewModel model)
        {
            var ConvertedAvailableDateTime = string.Empty;
            if (model.AppointmentDateLocalText != null)
            {
                TimeZoneInfo tzi = TimeZoneInfo.FindSystemTimeZoneById(model.TimeZoneValue);
                var datetime = model.AppointmentDateLocalText + " " + model.FromTime + ":" + model.ToTime + " " + model.FromAMPM;
                TimeSpan offset = tzi.GetUtcOffset(Convert.ToDateTime(datetime));
                var TimeZoneString = GetTimeZoneOffset(offset);
                ConvertedAvailableDateTime = (LocalToUtc(Convert.ToDateTime(datetime.ToString()), TimeZoneString)).ToString("yyyy-MM-dd HH:mm:ss:000");
            }
            var Clinicid = 0;
            var professiontype = 0;
            if (model.AppointmentSelectionType == 4)
            {
                Clinicid = Convert.ToInt32(model.Clinicid);
            }
            else
            {
                professiontype = model.AppointmentSelectionType;
            }
            SqlParameter[] parameters = new SqlParameter[9]{              
            new SqlParameter("@Name",string.IsNullOrEmpty(model.DoctorFullName)?"":StringCipher.Encrypt(model.DoctorFullName)), 
            new SqlParameter("@DoctorProfessionId",professiontype), 
            new SqlParameter("@countryId", model.countryid==null?0:model.countryid),
            new SqlParameter("@stateId", model.stateid==null?0:model.stateid),                    
            new SqlParameter("@postalCode",string.IsNullOrEmpty(model.postcode)?"" :StringCipher.Encrypt(model.postcode)),

Areas/Admin/Views/BookAppointment/Payment.cshtml
@model MyOnlineClinic.Web.Models.CreditCardViewModel
@{
    ViewBag.Title = "Payment";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Pay with credit card/voucher</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @using (Html.BeginForm("PayWithCreditCard", "BookAppointment", FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                        {
                            @Html.HiddenFor(m => m.AppointmentId, new { @value = ViewBag.AppointmentId })
                            @Html.HiddenFor(m => m.PatientId, new { @value = ViewBag.PatientId })
                            @Html.HiddenFor(m => m.DoctorLoginId, new { @value = ViewBag.DoctorId })
                            @Html.HiddenFor(m => m.AppointmentType, new { @value = ViewBag.ConsultType })
                            @Html.HiddenFor(m => m.ConsultType, new { @value = ViewBag.ConsultType })
                             
                            <div class="item form-group" id="dvPaidBy">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                                    Pay By: <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <select id="ddlPaidBy" name="ddlPaidBy" class="form-control col-md-7 col-xs-12 text_row">
                                        <option value="">---Select---</option>
                                        <option value="1">Voucher</option>
                                        <option value="2">Credit Card</option>
                                    </select>
                                </div>
                            </div>
                            <div class="item form-group" id="dvPayWithVoucher" style="display:none;">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                                    Voucher Number: <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(x => x.VoucherNumber, new { @class = "form-control col-md-7 col-xs-12" })
                                    @Html.ValidationMessage("Voucher")
                                </div>
                            </div>
                            <div class="item form-group" id="dvPayWithCreditCard" style="display:none;">
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                                        Card Holder Name <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextBoxFor(x => x.first_name, new { @class = "form-control col-md-7 col-xs-12", required = "required" })
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                                        Card Number <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextBoxFor(x => x.number, new { @class = "form-control col-md-7 col-xs-12", onkeypress = "return isNumber(event)", required = "required" })
                                        @Html.ValidationMessage("Invalid")
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                                        Expiry Month <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextBoxFor(x => x.expire_month, new { @class = "form-control col-md-7 col-xs-12", required = "required" })
                                        @*<input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="name" placeholder="both name(s) e.g Jon Doe" required="required" type="text">*@
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                                        Expiry Year <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextBoxFor(x => x.expire_year, new { @class = "form-control col-md-7 col-xs-12", required = "required" })
                                        @*<input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="name" placeholder="both name(s) e.g Jon Doe" required="required" type="text">*@
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                                        CVV <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextBoxFor(x => x.cvv2, new { @class = "form-control col-md-7 col-xs-12", required = "required" })
                                        @*<input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="name" placeholder="both name(s) e.g Jon Doe" required="required" type="text">*@
                                    </div>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button type="button" id="btnCancel" class="btn btn-primary">Cancel</button>
                                    <button id="send" type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery.creditCardValidator.js"></script>
@*<script src="/AdminAssets/js/validator/validator.js"></script>*@

<script>
    $(document).ready(function () {
        $('.date-picker').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_4"
        }, function (start, end, label) {

        });
        
        //To do validate card with jquery validations.
        window.validateCard = false;
        $('#number').validateCreditCard(function (result) {

            var cardType = $("#cardType");
            cardType.html('');

            var numberError = $("#number-error");
            numberError.html('');

            if (result.length_valid == true) {
                if (result.valid) {
                    validateCard = true;
                }
                cardType.append("<div class='alert alert-success'>Card Type is :- " + result.card_type.name + "</div>");
            }
            else {
                numberError.append("<div class='alert alert-danger' style='color:red;'>Please enter valid credit card details</div>");
            }
        });

        $('#ddlPaidBy').change(function () {
            var paidBy = $(this).val();

            var dvPayWithVoucher = $('#dvPayWithVoucher');
            var dvPayWithCreditCard = $('#dvPayWithCreditCard');

            dvPayWithVoucher.hide();
            dvPayWithCreditCard.hide();

            if (paidBy != '') {
                if (paidBy == '1') {
                    dvPayWithVoucher.show();
                }
                else {
                    dvPayWithCreditCard.show();
                }
            }

        })

    });
    // initialize the validator function
    validator.message['date'] = 'not a real date';

    // validate a field on "blur" event, a 'select' on 'change' event & a '.reuired' classed multifield on 'keyup':
    $('form')
        .on('blur', 'input[required], input.optional, select.required', validator.checkField)
        .on('change', 'select.required', validator.checkField)
        .on('keypress', 'input[required][pattern]', validator.keypress);

    $('.multi.required')
        .on('keyup blur', 'input', function () {
            validator.checkField.apply($(this).siblings().last()[0]);
        });

    // bind the validation to the form submit event
    //$('#send').click('submit');//.prop('disabled', true);

    $('form').submit(function (e) {
        e.preventDefault();
        var submit = true;
        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
            submit = false;
        }
        if (!validateCard) {
            $("#number-error").append("<div class='alert alert-danger' style='color:red;'>Please enter valid credit card details</div>");
            return false;
        }

        if (submit)
            this.submit();
        return false;
    });

    / FOR DEMO ONLY /
    $('#vfields').change(function () {
        $('form').toggleClass('mode2');
    }).prop('checked', false);

    $('#alerts').change(function () {
        validator.defaults.alerts = (this.checked) ? false : true;
        if (this.checked)
            $('form .alert').remove();
    }).prop('checked', false);

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }
</script>