Models/DoctorMembershipViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyOnlineClinic.Web.Models
{
    public class DoctorMembershipViewModel
    {
        public int DoctorId { get; set; }

        public int MembershipPaidBy { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public int VoucherID { get; set; }

        public string  VoucherNo { get; set; }
        public Guid LoginId { get; set; }
    }
}

Areas/Admin/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyOnlineClinic.Entity;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Web.Models;
using MyOnlineClinic.Web.Controllers;
using System.IO;
using System.Drawing;
using MyOnlineClinic.Web.Helper;
using MyOnlineClinic.Emailer;
using System.Configuration;
using System.Collections.ObjectModel;
namespace MyOnlineClinic.Web.Areas.Admin.Controllers
{
    public class DoctorController : BaseController
    {
        protected IFormsAuthentication _formsAuth;
        IDoctorService _doctorservice;
        IClinicService _clinicservice;
        ICountryService _countryService;
        ICityService _cityService;
        IOrganizationService _organizationservice;
        IUserService _userService;
        ITimeZoneService _timezoneservice;
        ILoginHelper _loginHelper;
        IProfessionTypeService _professiontypeservice;
        IStateService _stateservice;
        private readonly ITitleService _TitleServices;
        private readonly IGenderService _genderService;
        IUregisteredOrganizationService _unregisteredOrganizationService;
        IUnregisteredClinicService _unregisteredClinicService;
        IDoctorMembershipService _doctorMembershipService;
        IMembeshipVoucherService _membeshipVoucherService;
        IVoucherService _voucherService;
        IAppointmentService _AppointmentService;

        IPermissionInModuleService _permissioninmoduleService;
        IPatientService _patientServices;
        public DoctorController(ICountryService countryService, ICityService cityService, IFormsAuthentication formsAuth,
            IUserService userService, IDoctorService doctorservice, IOrganizationService organizationservice,
            ITimeZoneService timezoneservice, ILoginHelper loginHelper, IProfessionTypeService professiontypeservice,
            IClinicService clinicservice, ITitleService TitleServices, IGenderService genderService, IStateService stateservice,
            IUregisteredOrganizationService unregisteredOrganizationService, IUnregisteredClinicService unregisteredClinicService,
           IDoctorMembershipService doctorMembershipService, IMembeshipVoucherService membeshipVoucherService, IVoucherService voucherService, IPermissionInModuleService PermissionInModuleService, IPatientService patientServices, IAppointmentService AppointmentService)
        {
            _countryService = countryService;
            _cityService = cityService;
            _formsAuth = formsAuth;
            _userService = userService;
            _doctorservice = doctorservice;
            _organizationservice = organizationservice;
            _timezoneservice = timezoneservice;
            _loginHelper = loginHelper;
            _professiontypeservice = professiontypeservice;
            _clinicservice = clinicservice;
            _TitleServices = TitleServices;
            _genderService = genderService;
            _stateservice = stateservice;
            _unregisteredOrganizationService = unregisteredOrganizationService;
            _unregisteredClinicService = unregisteredClinicService;
            _doctorMembershipService = doctorMembershipService;
            _membeshipVoucherService = membeshipVoucherService;
            _voucherService = voucherService;
            _permissioninmoduleService = PermissionInModuleService;
            _patientServices = patientServices;
            _AppointmentService = AppointmentService;
        }
        //
        // GET: /Doctor/Doctor/
        public ActionResult Add(int? id)
        {
            // RegisterViewModel doctor = new RegisterViewModel();

            if (id.HasValue)
            {
                var cModel = _doctorservice.GetDoctorById(Convert.ToInt32(id)).Select(x => new RegisterViewModel
                {
                    TitleId = x.Title,
                    FirstName = StringCipher.Decrypt(x.FirstName),
                    MiddleName = StringCipher.Decrypt(x.MiddleName),
                    SurName = StringCipher.Decrypt(x.SurName),
                    Email = StringCipher.Decrypt(x.Email),
                    DOB = x.DOB,
                    GenderId = x.Gender,
                    MobileNumber = StringCipher.Decrypt(x.MobileNumber),
                    FaxNumber = StringCipher.Decrypt(x.FaxNumber),
                    ClinicID = Convert.ToInt32(x.ClinicID),
                    City = x.City,
                    State = x.State,
                    CountryId = x.CountryId,
                    Profession = x.Profession,
                    PostCode = StringCipher.Decrypt(x.PostCode),
                    Timezone = StringCipher.Decrypt(x.TimeZoneString),
                    //ClinicID = _clinicService.GetClinicById(id).cli,
                    PhoneNumber = StringCipher.Decrypt(x.PhoneNumber),
                    Address1 = StringCipher.Decrypt(x.Address1),
                    Address2 = StringCipher.Decrypt(x.Address2),
                    OrgId = x.OrgId,
                    //  ProfilePic = _userService.Find(x.LoginId).Avatar,

                    IsActive = x.IsActive,
                    MemberId = x.MemberId,
                    LoginId = x.LoginId,
                    Createdby = (Guid)x.CreatedBy,
                    PhoneCode = x.PhoneCode,
                    LanguageSpoken = StringCipher.Decrypt(x.LanguageSpoken),
                    ProfessionCategory = x.ProfessionCategory,
                    IntrestArea = StringCipher.Decrypt(x.IntrestArea),
                    qualification = StringCipher.Decrypt(x.qualification),
                    AHPRANo = StringCipher.Decrypt(x.AHPRANo),
                    VideoProviderNo = StringCipher.Decrypt(x.VideoProviderNo),
                    HomeVisitProviderNo = StringCipher.Decrypt(x.HomeVisitProviderNo),
                    ClinicProviderNo = StringCipher.Decrypt(x.ClinicProviderNo),
                    PrescriberNo = StringCipher.Decrypt(x.PrescriberNo),
                    DoctorProfile = StringCipher.Decrypt(x.DoctorProfile),
                    TimeZoneId = Common.GetTimeZoneStandardIdAndDisplayName(x.TimeZoneString)
                    // SignaturePic = _doctorservice.GetDoctorById(x.MemberId)

                    //  OrganizationAddress=_organizationservice.GetOrganizationAddressbyId(Convert.ToInt32(x.OrgId)),
                }).FirstOrDefault();
                try
                {

                    cModel.OrgClinicIdsList = _userService.GetClinicList(Convert.ToInt32(id), (int)RoleType.Doctor).Select(x =>
                       new RegisterViewModel
                       {
                           UserClinicId = x.ClinicId,
                           UserClinicName = StringCipher.Decrypt(x.Clinics.ClinicName),
                           UserClinicAddress1 = StringCipher.Decrypt(x.Clinics.Address1),
                           UserClinicAddress2 = StringCipher.Decrypt(x.Clinics.Address2),
                           UserClinicPostalCode = StringCipher.Decrypt(x.Clinics.PostCode),
                           UserClinicCountryId = x.Clinics.Country,
                           UserClinicStateId = x.Clinics.State,
                           UserClinicCityId = x.Clinics.City,
                           ClinicProviderNo = StringCipher.Decrypt(x.ClinicProviderNo)


                       }).ToList();
                }
                catch { }
                if (cModel != null)
                {

                    cModel.ProfilePic = _userService.Find(cModel.LoginId).Avatar;
                    if (_organizationservice.GetOrganizationById(cModel.OrgId) != null)
                    {
                        cModel.organizationName = StringCipher.Decrypt(_organizationservice.GetOrganizationById(cModel.OrgId).OrganizationName);
                    }
                    if (_doctorservice.GetDoctorList().Where(y => y.MemberId == cModel.MemberId).Select(y => y.SignaturePic).FirstOrDefault() != null)
                    {
                        cModel.SignaturePic = _doctorservice.GetDoctorList().Where(y => y.MemberId == cModel.MemberId).Select(y => y.SignaturePic).FirstOrDefault();
                    }
                }
                BindDropDown(cModel);
                return View(cModel);
            }
            else
            {
                RegisterViewModel doctor = new RegisterViewModel();
                BindDropDown(doctor);
                return View(doctor);
            }
        }
        [HttpPost]
        [AllowAnonymous]
        //[ValidateAntiForgeryToken]
        public ActionResult Add(RegisterViewModel model, HttpPostedFileBase ProfilePic, HttpPostedFileBase Signaturepic)
        {
            if (model.MemberId > 0)
            {
                if (Signaturepic != null && Signaturepic.ContentLength > 0)
                {
                    UploadSignature(model, Signaturepic);
                }
                else
                {
                    model.SignaturePic = model.SignaturePic;
                }
                if (ProfilePic != null)
                {
                    _loginHelper.UploadImage(model, ProfilePic);
                    var userid = _userService.Find(model.LoginId);
                    userid.Avatar = model.ProfilePic;
                    _userService.Update(userid);
                }
                MyOnlineClinic.Entity.Doctor profile = null;
                profile = model.AdminEditDoctor(model);
                TimeZoneInfo tzi = TimeZoneInfo.FindSystemTimeZoneById(model.TimeZoneId);
                TimeSpan offset = tzi.GetUtcOffset(Convert.ToDateTime(DateTime.UtcNow));
                profile.TimeZoneString = Common.GetTimeZoneOffset(offset);

                _doctorservice.Update(profile);
                var length = entitiesDb.UserClinics.Where(w => w.UserId == model.MemberId && w.Type == (int)RoleType.Doctor).ToList();
                if (length != null)
                {

Areas/Doctor/Controllers/ContactUsController.cs
using MyOnlineClinic.Entity;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Web.Controllers;
using MyOnlineClinic.Web.Models;
using System.Web.Mvc;
using MyOnlineClinic.Emailer;

namespace MyOnlineClinic.Web.Areas.Doctor.Controllers
{
    public class ContactUsController : BaseController
    {
        private readonly ICommunication _Communication;
        private readonly IReportProblemService _reportProblemService;
        private readonly IDoctorService _doctorService;
        private readonly IAdminUserService _adminUserService;
        public ContactUsController(ICommunication Communication, IReportProblemService reportproeblemService, IDoctorService doctorService, IAdminUserService adminUserService)
        {
            _Communication = Communication;
            _reportProblemService = reportproeblemService;
            _doctorService = doctorService;
            _adminUserService = adminUserService;
        }

        [HttpGet]
        public ActionResult Index()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Index(CommunicationViewModel model)
        {
            var adminLogiid = _adminUserService.FindAdmin((int)RoleType.ADMIN).LoginId;
            var Contact = new ContectUs
            {
                Name = model.ContactUsName,
                Email = model.ContactUsEmail,
                Message = model.ContactUsMessage,
                SenderId = base.loginUserModel.LoginId,
                RecevierId = adminLogiid,
                IsRead = false,
                IsCompleted = false,
                RoleType = (int)RoleType.Doctor,
                Subject=model.Subject
            };
            if (Contact != null)
            {
                _Communication.Add(Contact);
                var fileUrl = Server.MapPath("~/EmailTemplates/Communication.html");
                string html = System.IO.File.ReadAllText(fileUrl);
                html = html.Replace("@UserName", model.ContactUsName);
                html = html.Replace("@Email", model.ContactUsEmail);
                html = html.Replace("@Message", model.ContactUsMessage);
                EmailService objEmail = new EmailService();
                objEmail.SendEmail("Contact us", html, "mocbookings@doctortoyou.com.au", "tma@myonlineclinic.com.au");
                return Redirect(Request.UrlReferrer.ToString());
            }
            return View(model);
        }

    }
}

Areas/Doctor/Controllers/DoctorPastConsultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyOnlineClinic.Entity;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Web.Models;
using MyOnlineClinic.Web.Controllers;
using System.IO;
using System.Drawing;
using MyOnlineClinic.Web.Helper;
using MyOnlineClinic.Emailer;
using System.Configuration;
using System.Collections.ObjectModel;

namespace MyOnlineClinic.Web.Areas.Doctor.Controllers
{
    public class DoctorPastConsultController : BaseController
    {
         private readonly IAppointmentService _AppointmentService;
        private readonly IUserService _userService;
        public DoctorPastConsultController(IAppointmentService AppointmentService, IUserService userService)
        {
            _AppointmentService = AppointmentService;
            _userService = userService;
        }
        //
        // GET: /Doctor/DoctorPastConsult/
        public ActionResult Index()
        {
            var commonUtilities = new CommonUtilities();

            var Pastconsult = _AppointmentService.GetAppointmentList().Select(x => new AppointmentViewModel
            {
                AppointmentDateLocalText = x.AppointmentDateLocal.ToString("dd/MM/yyyy h:mm tt"),
                AppointmentId = x.AppointmentId,
                AppointmentTypeText = (x.AppointmentType == (int)AppointmentType.VideoConsult ?
                                      commonUtilities.GetDisplayName(AppointmentType.VideoConsult) :
                                      x.AppointmentType == (int)AppointmentType.ClinicVisit ?
                                      commonUtilities.GetDisplayName(AppointmentType.ClinicVisit) :
                                      commonUtilities.GetDisplayName(AppointmentType.HomeVisit)),

  
                PatientName = StringCipher.Decrypt(_userService.Find(x.PatientLoginId).Member.FirstName) + " " + StringCipher.Decrypt(_userService.Find(x.PatientLoginId).Member.SurName),
                AppointmentDateUtc = x.AppointmentDateUtc,
                AppointmentStatus = x.AppointmentStatus,
                IsSoapNotesAdded = _AppointmentService.CheckSoapNotes(x.AppointmentId) ? true : false

            }).Where(x => x.AppointmentStatus != (int)AppointmentStatus.Pending && x.AppointmentStatus != (int)AppointmentStatus.Approved || (x.IsSoapNotesAdded == true && x.AppointmentStatus == (int)AppointmentStatus.Completed)).ToList();
            // x.DoctorLoginId == base.loginUserModel.LoginId &&
            var a = (int)AppointmentStatus.Pending;


            return PartialView("_doctorPastConsult", Pastconsult);
        }
        public JsonResult SosapNotes(int AppointmentId)
        {
            var SOap = _AppointmentService.GetSoapId(AppointmentId);
            return Json(SOap, JsonRequestBehavior.AllowGet);
        }
	}
}

Areas/Doctor/Controllers/ReportProblemController.cs
using MyOnlineClinic.Entity;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Web.Controllers;
using MyOnlineClinic.Web.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web.Mvc;
using MyOnlineClinic.Web.Helper;
using System.Data.SqlClient;
using MyOnlineClinic.Migrator;
using System.Globalization;

namespace MyOnlineClinic.Web.Areas.Doctor.Controllers
{
    public class ReportProblemController : BaseController
    {
        private readonly IAdminUserService _adminUserService;
        private readonly IReportProblemService _reportProblemService;

        public ReportProblemController(IAdminUserService adminUserService, IReportProblemService reportProblemService)
        {
            _adminUserService = adminUserService;
            _reportProblemService = reportProblemService;
        }
        [HttpGet]
        public ActionResult Index()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Index(ReportProblemViewModel model)
        {
            var adminLogiid = _adminUserService.FindAdmin((int)RoleType.ADMIN).LoginId;
            var Report = new ReportProblem
            {
                ReportProblemSubject = model.ReportProblemSubject,
                SenderId = base.loginUserModel.LoginId,
                RecevierId = adminLogiid,
                IsRead = false,
                IsCompleted = false,
                RoleType = (int)RoleType.Doctor
            };
            if (Report != null)
            {
                _reportProblemService.Add(Report);
            }
            return View(model);
        }
    }
}

Areas/Organizations/Views/Doctor/DoctorMembership.cshtml
@model MyOnlineClinic.Web.Models.DoctorMembershipViewModel
@{
    ViewBag.Title = "DoctorMembership";
    Layout = "~/Areas/Organizations/Views/Shared/_OrganizationLayout.cshtml";
}
@using JQueryUIHelpers;
@using Share.Bonnet.AjaxDropDownList;
@Scripts.Render("~/bundles/bonnet")
<script src="/scripts/jquery.plugin.js"></script>
<script src="/scripts/jquery.datepick.js"></script>
<link href="~/Scripts/jquery.datepick.css" rel="stylesheet" />
<section class="content-header staff">
    <h1 class="underline40">
        Doctor Membership
    </h1>
</section>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-7 first_layer">
            <div class="form-horizontal" id="style-3">
                <div class="box-body">
                    @using (Html.BeginForm("DoctorMembership", "Doctor", FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                    {
                        @Html.HiddenFor(m => m.DoctorId)
                        @Html.HiddenFor(m => m.LoginId)
                        <div class="form-group role" style="margin-top:-3px;">
                  <label for="inputEmail3" class="col-sm-4 control-label">Membership StartDate:</label>
                            
                            <div class="col-sm-6">
                                @Html.TextBoxFor(x => x.StartDate, new { @class = "form-control", name = "StartDate", placeholder = "Select Membership Start Date", required = "required" })
                            </div>
                        </div>
                        <div class="form-group role" style="margin-top:-3px;">
                  <label for="inputEmail3" class="col-sm-4 control-label">Voucher No:</label>
                            <div class="col-sm-6">
                                @Html.TextBoxFor(x => x.VoucherNo, new { @class = "form-control", name = "VoucherNo", placeholder = "Enter Voucher No", required = "required" })
                            </div>
                        </div>
                        <div class="item form-group" style="text-align:center; font-weight:bold; color:red;">
                            @(Convert.ToString(TempData["ErrorMessage"]))
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3" style="text-align:center;">
                                                <button type="submit" class="btn btn-primary">Cancel</button>
                                                <button type="submit" class="btn btn-success">Submit</button>
                                            </div>
                                        </div>    
                    }
                </div>
        </div>
    </div>
</div>
    </div>
<script src="/AdminAssets/js/validator/validator.js"></script>
<script>
    $('#btnCancel').click(function () {
        window.location = "/admin/Doctor/DoctorList";
    })

    $(document).ready(function () {
        var currentDateTime = new Date();
        var year = currentDateTime.getFullYear();
        var month = currentDateTime.getMonth();
        var date = currentDateTime.getDate();

        $('#StartDate').datepick({ dateFormat: 'dd/mm/yyyy', minDate: 0 });
    });
    // initialize the validator function
    validator.message['date'] = 'not a real date';

    // validate a field on "blur" event, a 'select' on 'change' event & a '.reuired' classed multifield on 'keyup':
    $('form')
        .on('blur', 'input[required], input.optional, select.required', validator.checkField)
        .on('change', 'select.required', validator.checkField)
        .on('keypress', 'input[required][pattern]', validator.keypress);

    $('.multi.required')
        .on('keyup blur', 'input', function () {
            validator.checkField.apply($(this).siblings().last()[0]);
        });

    // bind the validation to the form submit event
    //$('#send').click('submit');//.prop('disabled', true);

    $('form').submit(function (e) {
        e.preventDefault();
        var submit = true;
        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
            submit = false;
        }
        if (submit)
            this.submit();
        return false;
    });

    /* FOR DEMO ONLY */
    $('#vfields').change(function () {
        $('form').toggleClass('mode2');
    }).prop('checked', false);

    $('#alerts').change(function () {
        validator.defaults.alerts = (this.checked) ? false : true;
        if (this.checked)
            $('form .alert').remove();
    }).prop('checked', false);
</script>

Areas/Organizations/Views/Doctor/MyPatient.cshtml
@model List<MyOnlineClinic.Web.Models.RegisterViewModel>
@{
    ViewBag.Title = "MyPatient";
    Layout = "~/Areas/Organizations/Views/Shared/_OrganizationLayout.cshtml";
}
<section class="content-header" style="margin-top:45px;">
    <h1 class="underline35">
        Patients List
    </h1>
    <ol class="breadcrumb">
        <li style="margin-right: 5px !important;"><button type="button" class="btn btn-success new">Back</button></li>
    </ol>
</section>
<div class="container-fulid">
    <div class="row">
        <div class="col-md-12 eight_layer">
            <div class="table-responsive data">
                <table id="mytable" class="table table-hover table-bordered">
                    <thead style="color:#fff;">
                        <tr>
                            <th class="top">Patient</th>
                            <th class="top"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int count = 1;}
                        @foreach (var item in Model)
                        {

                            <tr class="info">

                                <td>@item.FullName</td>
                                <td>
                                    <a class="successbutton" href="#" data-toggle="tooltip" data-placement="left">

                                        <button class="button" style="vertical-align:middle"><span>Assign Voucher</span></button>

                                    </a>
                                    <a href="#" data-toggle="tooltip" class="btn btn-success" data-placement="left">Clinical Dashbord</a>
                                </td>
                            </tr>
                            count = count + 1;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
</div>
<script src="~/AdminAssets/js/datatables/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        var oTable = $('#example').dataTable({
            "bProcessing": true,
            "iDisplayLength": 10,
            "bPaginate": true,
            "sPaginationType": "full_numbers"
        });
        $('[data-toggle="tooltip"]').tooltip();
        //$("#btnNew").click(function () {
        //    window.location.href = "/admin/Gender/add";
        //});

        DisableButton();
        var favorite = [];
        $("#selecctall").click(function (event) {  //on click
            if (this.checked) {
                $("input[name='UserApproval']").each(function () { //loop through each checkbox
                    if (this.checked !== true) {
                        this.checked = true;  //select all checkboxes with class "checkbox1"
                        favorite.push($(this).val());
                    }
                });
            } else {
                $("input[name='UserApproval']").each(function () { //loop through each checkbox
                    this.checked = false; //deselect all checkboxes with class "checkbox1"
                    favorite.pop($(this).val());
                });
            }
            $("#serviceIds").val(favorite);
            $("#ActivateIds").val(favorite);
            DisableButton();

        });

         $(document).on('click', "input[name='UserApproval']", function (event) {
            if (this.checked == true) {
                favorite.push($(this).val());
            }
            else {
                favorite.pop();
            }
            $("#serviceIds").val(favorite);
            $("#ActivateIds").val(favorite);
            DisableButton();
        });

        $("#btnDelete").click(function () {
            var options = {
                "backdrop": "static"
            };
            $('#basicModal').modal(options);
        });

        $("#btnActivate").click(function () {
            var options = {
                "backdrop": "static"
            };
            $('#ActivateModal').modal(options);
        });
        $("#btnBack").on("click", function () {
            window.history.back();
        });
    });

    function DisableButton() {
        if ($("#serviceIds").val() == '') {
            $("#btnDelete").attr('disabled', 'disabled');
        }
        else {
            $("#btnDelete").removeAttr('disabled', 'disabled');
        }
        if ($("#ActivateIds").val() == '') {
            $("#btnActivate").attr('disabled', 'disabled');
        }
        else {
            $("#btnActivate").removeAttr('disabled', 'disabled');
        }
    }


</script>