Areas/Doctor/Controllers/ContactUsController.cs
using MyOnlineClinic.Entity;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Web.Controllers;
using MyOnlineClinic.Web.Models;
using System.Web.Mvc;
using MyOnlineClinic.Emailer;

namespace MyOnlineClinic.Web.Areas.Doctor.Controllers
{
    public class ContactUsController : BaseController
    {
        private readonly ICommunication _Communication;
        private readonly IReportProblemService _reportProblemService;
        private readonly IDoctorService _doctorService;
        private readonly IAdminUserService _adminUserService;
        public ContactUsController(ICommunication Communication, IReportProblemService reportproeblemService, IDoctorService doctorService, IAdminUserService adminUserService)
        {
            _Communication = Communication;
            _reportProblemService = reportproeblemService;
            _doctorService = doctorService;
            _adminUserService = adminUserService;
        }

        [HttpGet]
        public ActionResult Index()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Index(CommunicationViewModel model)
        {
            var adminLogiid = _adminUserService.FindAdmin((int)RoleType.ADMIN).LoginId;
            var Contact = new ContectUs
            {
                Name = model.ContactUsName,
                Email = model.ContactUsEmail,
                Message = model.ContactUsMessage,
                SenderId = base.loginUserModel.LoginId,
                RecevierId = adminLogiid,
                IsRead = false,
                IsCompleted = false,
                RoleType = (int)RoleType.Doctor,
                Subject=model.Subject
            };
            if (Contact != null)
            {
                _Communication.Add(Contact);
                var fileUrl = Server.MapPath("~/EmailTemplates/Communication.html");
                string html = System.IO.File.ReadAllText(fileUrl);
                html = html.Replace("@UserName", model.ContactUsName);
                html = html.Replace("@Email", model.ContactUsEmail);
                html = html.Replace("@Message", model.ContactUsMessage);
                EmailService objEmail = new EmailService();
                objEmail.SendEmail("Contact us", html, "mocbookings@doctortoyou.com.au", "tma@myonlineclinic.com.au");
                return Redirect(Request.UrlReferrer.ToString());
            }
            return View(model);
        }

    }
}

Areas/Patients/Controllers/ContactUsController.cs
using MyOnlineClinic.Entity;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Web.Controllers;
using MyOnlineClinic.Web.Models;
using System.Web.Mvc;
using MyOnlineClinic.Emailer;


namespace MyOnlineClinic.Web.Areas.Patients.Controllers
{
    public class ContactUsController : BaseController
    {
        private readonly ICommunication _Communication;
        private readonly IReportProblemService _reportProblemService;
        private readonly IDoctorService _doctorService;
        private readonly IAdminUserService _adminUserService;
        public ContactUsController(ICommunication Communication, IReportProblemService reportproeblemService, IDoctorService doctorService, IAdminUserService adminUserService)
        {
            _Communication = Communication;
            _reportProblemService = reportproeblemService;
            _doctorService = doctorService;
            _adminUserService = adminUserService;
        }
        [HttpGet]
        public ActionResult Index()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Index(CommunicationViewModel model)
        {
            var adminLogiid = _adminUserService.FindAdmin((int)RoleType.ADMIN).LoginId;
            var Contact = new ContectUs
            {
                Name = model.ContactUsName,
                Email = model.ContactUsEmail,
                Message = model.ContactUsMessage,
                SenderId = base.loginUserModel.LoginId,
                RecevierId = adminLogiid,
                IsRead = false,
                IsCompleted = false,
                RoleType = (int)RoleType.Patient,
                Subject = model.Subject
            };
            if (Contact != null)
            {
                _Communication.Add(Contact);
                var fileUrl = Server.MapPath("~/EmailTemplates/Communication.html");
                string html = System.IO.File.ReadAllText(fileUrl);
                html = html.Replace("@UserName", model.ContactUsName);
                html = html.Replace("@Email", model.ContactUsEmail);
                html = html.Replace("@Message", model.ContactUsMessage);
                EmailService objEmail = new EmailService();
                objEmail.SendEmail("Contact us", html, "mocbookings@doctortoyou.com.au", "tma@myonlineclinic.com.au");
                return Redirect(Request.UrlReferrer.ToString());
            }
            return View(model);
        }

    }
}

Areas/Doctor/Views/ContactUs/Index.cshtml
@model MyOnlineClinic.Web.Models.CommunicationViewModel
@{
    ViewBag.Title = "Index";
    Layout = "/Areas/Patients/Views/Shared/_PatientPartial.cshtml";
}



<div id="NewConsultation">
    <h3 class="from_title">Report a Problem</h3>
    <div class="container-fluid">
        <div class="row table">
            <div class="content_boxs" style=" height: 420px; width: 99%; ">
                <div align="left">
                    <div class="from_box">
                        <fieldset>
                            @using (Html.BeginForm("Index", "ContactUs", FormMethod.Post, new { @class = "form-horizontal form-label-left", enctype = "multipart/form-data" }))
                            {

                                <div class="tr_box">
                                    <div class="td_1">
                                        <span class="lbl_text">
                                            Name
                                        </span>
                                    </div>
                                    <div class="input_box1 rel1">
                                        <div class=" col-sm-8 col-xs-12">
                                            @Html.TextBoxFor(x => x.ContactUsName, new { @class = "form-control col-md-7 col-xs-12 text_row", name = "ReportProblemSubject", required = "required" })
                                        </div>

                                    </div>
                                </div>
                                <div class="tr_box">
                                    <div class="td_1">
                                        <span class="lbl_text">
                                          Email
                                        </span>
                                    </div>
                                    <div class="input_box1 rel1">
                                        <div class=" col-sm-8 col-xs-12">
                                            @Html.TextBoxFor(x => x.ContactUsEmail, new { @class = "form-control col-md-7 col-xs-12 text_row", name = "ReportProblemSubject", required = "required" })
                                        </div>

                                    </div>
                                </div>
                                <div class="tr_box">
                                    <div class="td_1">
                                        <span class="lbl_text">
                                           Subject
                                        </span>
                                    </div>
                                    <div class="input_box1 rel1">
                                        <div class=" col-sm-8 col-xs-12">
                                            @Html.TextBoxFor(x => x.Subject, new { @class = "form-control col-md-7 col-xs-12 text_row", name = "ReportProblemSubject", required = "required" })
                                        </div>

                                    </div>
                                </div>
                                  <div class="tr_box">
                                    <div class="td_1">
                                        <span class="lbl_text">
                                           Message
                                        </span>
                                    </div>
                                    <div class="input_box1 rel1">
                                        <div class=" col-sm-8 col-xs-12">
                                            @Html.TextBoxFor(x => x.ContactUsMessage, new { @class = "form-control col-md-7 col-xs-12 text_row", name = "ReportProblemSubject", required = "required" })
                                        </div>

                                    </div>
                                </div>

                                <input class="btn btn-default pull-right personal" type="submit" id="savenewconsult" value="Save">
                            }
                        </fieldset>


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>