Models/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MyOnlineClinic.Entity;

namespace MyOnlineClinic.Web.Models
{
    public class DashboardViewModel
    {
        public int ClinicCount { get; set; }
        public int OrganizationCount { get; set; }
        public int PatientCount { get; set; }
        public int DoctorCount { get; set; }
        public int AppointmentCount { get; set; }
        public List<PermissionInModule> ModuleList { get; set; }
    }
}

Areas/Admin/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyOnlineClinic.Web.Controllers;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Entity;
using MyOnlineClinic.Web.Models;
using System.IO;
using MyOnlineClinic.Web.Helper;
using MyOnlineClinic.Emailer;
using System.Configuration;
using System.Collections.ObjectModel;
using System.Globalization;

namespace MyOnlineClinic.Web.Areas.Admin.Controllers
{
    [AuthorizeRole("Admin")]
    public class DashBoardController : BaseController
    {
        #region "VARIABLES"
        protected readonly IUserService _userService;
        private readonly IOrganizationService _organiztionService;
        private readonly IClinicService _clinicService;
        private readonly ILoginHelper _loginHelper;
        private readonly ICountryService _countryService;
        private readonly ICityService _cityService;
        private readonly ILookUpModuleService _moduleService;
        private readonly IPermissionsService _permissionService;
        private readonly ILookUpUserRolesService _roleService;
        private readonly IPermissionInModuleService _permissionInModuleService;
        private readonly ITimeZoneService _timeZoneService;
        private readonly ITitleService _titleService;
        private readonly IGenderService _genderService;
        private readonly IStateService _stateService;
        private readonly IAdminUserService _adminUserService;
        private readonly IDoctorService _doctorService;
        private readonly IAppointmentService _appointmentService;
        #endregion

        #region "CONSTRUCTOR"
        public DashBoardController(IUserService userService, IOrganizationService organiztionService, IClinicService clinicService,
            ILoginHelper loginHelper, ICountryService countryService, ICityService cityService, ILookUpModuleService moduleService,
            IPermissionsService permissionService, ILoginHelper loginService, ILookUpUserRolesService roleService, IAdminUserService adminUserService,
            IPermissionInModuleService permissioninmoduleService, ITimeZoneService timezoneService,
            ITitleService TitleServices, IGenderService genderService, IStateService stateService, IDoctorService doctorService,
            IAppointmentService appointmentService)
        {
            _userService = userService;
            _organiztionService = organiztionService;
            _clinicService = clinicService;
            _loginHelper = loginHelper;
            _countryService = countryService;
            _cityService = cityService;
            _moduleService = moduleService;
            _permissionService = permissionService;
            _roleService = roleService;
            _permissionInModuleService = permissioninmoduleService;
            _timeZoneService = timezoneService;
            _titleService = TitleServices;
            _genderService = genderService;
            _stateService = stateService;
            _adminUserService = adminUserService;
            _doctorService = doctorService;
            _appointmentService = appointmentService;
        }
        #endregion

        #region "ACTIONS"
        public new ActionResult Profile()
        {
            Login model = _userService.Find(base.loginUserModel.LoginId);
            UserViewModel userModel = new UserViewModel();
            userModel.FirstName = StringCipher.Decrypt(model.Member.FirstName) + " " + StringCipher.Decrypt(model.Member.SurName);
            userModel.LoginName = StringCipher.Decrypt(model.LoginName);
            userModel.EmailAddress = StringCipher.Decrypt(model.Email);
            userModel.FaxNumber = StringCipher.Decrypt(model.Member.FaxNumber);
            userModel.DOB = model.Member.DOB;
            userModel.PostCode = StringCipher.Decrypt(model.Member.PostCode);
            userModel.PhoneNumber = StringCipher.Decrypt(model.Member.PhoneNumber);
            userModel.MobileNumber = StringCipher.Decrypt(model.Member.MobileNumber);
            userModel.Address1 = StringCipher.Decrypt(model.Member.Address1);
            userModel.Address2 = StringCipher.Decrypt(model.Member.Address2);
            userModel.MemberId = model.Member.MemberId;
            userModel.LoginId = model.LoginId;
            userModel.ProfilePic = model.Avatar;
            return View(userModel);
        }

        [HttpPost]
        public ActionResult Profile(UserViewModel model, HttpPostedFileBase ProfilePic)
        {
            _loginHelper.UpdateProfile(model, ProfilePic, base.loginUserModel.LoginId);
            Response.Redirect("Profile");
            return View(model);
        }

        public ActionResult UsersList()
        {
            var users = _adminUserService.GetAllAdminUser().Select(x =>
               new UserViewModel
               {
                   Fullname = StringCipher.Decrypt(_titleService.GetTitleById(x.Title).TitleName) + " " + StringCipher.Decrypt(x.FirstName) + " " + StringCipher.Decrypt(x.SurName),
                   EmailAddress = StringCipher.Decrypt(x.Email),
                   PhoneNumber = StringCipher.Decrypt(x.PhoneNumber),
                   MobileNumber = StringCipher.Decrypt(x.MobileNumber),
                   FaxNumber = StringCipher.Decrypt(x.FaxNumber),
                   ModifiedDate = x.ModifiedDate ?? DateTime.Now,
                   PostCode = StringCipher.Decrypt(x.PostCode),
                   MemberId = x.MemberId,
                   RoleName = x.OrgUsreRole != 0 ? StringCipher.Decrypt(_roleService.GetUserRolesById(x.OrgUsreRole).RoleName) : string.Empty,
                   IsActive = x.IsActive,
                   ProfilePic = _userService.Find(x.LoginId).Avatar,
                   LastUpdateDateInString = x.ModifiedDate == null ? "" : Common.UtcToLocal(Convert.ToDateTime(x.ModifiedDate), x.TimeZoneString).ToString("dd/MM/yyyy h:mm tt"),
                   TimeZoneDisplayName = Common.GetTimeZoneStandardIdAndDisplayName(x.TimeZoneString, true)
               }).ToList();
            return View(users);
        }

        [HttpPost]
        public ActionResult UsersList(SearchParametersViewModel searchModel)
        {
            var users = _adminUserService.GetAllAdminUser().Select(x =>
               new UserViewModel
               {
                   Fullname = StringCipher.Decrypt(x.FirstName) + " " + StringCipher.Decrypt(x.SurName),

                   EmailAddress = StringCipher.Decrypt(x.Email),
                   PhoneNumber = StringCipher.Decrypt(x.PhoneNumber),
                   MobileNumber = StringCipher.Decrypt(x.MobileNumber),
                   FaxNumber = StringCipher.Decrypt(x.FaxNumber),
                   LastUpdateDateInString = x.ModifiedDate == null ? "" : Common.UtcToLocal(Convert.ToDateTime(x.ModifiedDate), x.TimeZoneString).ToString("dd/MM/yyyy h:mm tt"),
                   TimeZoneDisplayName = Common.GetTimeZoneStandardIdAndDisplayName(x.TimeZoneString, true),
                   PostCode = StringCipher.Decrypt(x.PostCode),
                   MemberId = x.MemberId,
                   RoleName = x.OrgUsreRole != 0 ? StringCipher.Decrypt(_roleService.GetUserRolesById(x.OrgUsreRole).RoleName) : string.Empty,
                   IsActive = x.IsActive
               }).ToList();

            //RoleList = _roleService.GetUserRolesList().Where(x => x.RoleType.RoleTypeName == StringCipher.Encrypt("Moc Admin")).Select(x => new RoleListViewModel
            //    {
            //        Id = x.Id,
            //        RoleName = StringCipher.Decrypt(x.RoleName)
            //    }).ToList()

            users = users.Where(x =>
                 ((searchModel.StaffName != null && x.Fullname.IndexOf(searchModel.StaffName, StringComparison.OrdinalIgnoreCase) >= 0) || searchModel.StaffName == null)
                  &&

                  ((searchModel.RoleName != null && x.RoleName.IndexOf(searchModel.RoleName, StringComparison.OrdinalIgnoreCase) >= 0) || searchModel.RoleName == null)
                    &&
                 ((searchModel.Email != null && x.EmailAddress.Contains(searchModel.Email) || searchModel.Email == null))
                &&
                   ((searchModel.ActivationStatus != null && x.IsActive == Convert.ToBoolean(searchModel.ActivationStatus)) ||
                         searchModel.ActivationStatus == null)

               ).ToList();

            return View(users);

        }

        public ActionResult Details(int id)
        {

            var model = _adminUserService.GetUsersById(id).Select(x => new UserViewModel
            {
                FirstName = StringCipher.Decrypt(x.FirstName),
                MiddleName = StringCipher.Decrypt(x.MiddleName),
                SurName = StringCipher.Decrypt(x.SurName),
                OrgUsreRole = x.OrgUsreRole,
                EmailAddress = StringCipher.Decrypt(x.Email),
                CountryId = x.CountryId,
                State = x.State,
                City = x.City,
                PhoneNumber = StringCipher.Decrypt(x.PhoneNumber),
                MobileNumber = StringCipher.Decrypt(x.MobileNumber),
                PostCode = StringCipher.Decrypt(x.PostCode),
                Address1 = StringCipher.Decrypt(x.Address1),
                Address2 = StringCipher.Decrypt(x.Address2),
                FaxNumber = StringCipher.Decrypt(x.FaxNumber),
                LoginId = x.LoginId,
                MemberId = x.MemberId,
                DobInString = Convert.ToDateTime(x.DOB).ToString("dd-MM-yyyy"),
                TimezoneId = Common.GetTimeZoneStandardIdAndDisplayName(x.TimeZoneString, true)
            }).ToList().FirstOrDefault();

            if (model.State != null)
            {
                model.StateName = StringCipher.Decrypt(_stateService.GetStateById(model.State).StateName);
            }
            if (model.CountryId != null)
            {

Areas/Clinic/Controllers/DashboardController.cs
using MyOnlineClinic.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyOnlineClinic.RepositoryService;
using MyOnlineClinic.Entity;
using MyOnlineClinic.Web.Helper;
using MyOnlineClinic.Web.Models;

namespace MyOnlineClinic.Web.Areas.Clinic.Controllers
{
    public class DashboardController : BaseController
    {

        ILoginHelper _loginService;
        IUserService _userService;
        private readonly IOrganizationService _organiztionService;
        private readonly IClinicService _clinicService;
        private readonly IPermissionInModuleService _permissioninmoduleService;
        private readonly IDoctorService _doctorService;

        public DashboardController(ILoginHelper loginService, IUserService userService, IOrganizationService organiztionService,
           IClinicService clinicService, IPermissionInModuleService permissioninmoduleService,IDoctorService doctorService)
        {
            _loginService = loginService;
            _userService = userService;
            _organiztionService = organiztionService;
            _clinicService = clinicService;
            _permissioninmoduleService = permissioninmoduleService;
            _doctorService = doctorService;
        }
        public ActionResult Profile()
        {
            Login model = _userService.Find(base.loginUserModel.LoginId);
            UserViewModel userModel = new UserViewModel(model);
            userModel.FirstName = StringCipher.Decrypt(userModel.FirstName);
            userModel.MiddleName = StringCipher.Decrypt(userModel.MiddleName);
            userModel.SurName = StringCipher.Decrypt(userModel.SurName);
            userModel.Address1 = StringCipher.Decrypt(userModel.Address1);
            userModel.Address2 = StringCipher.Decrypt(userModel.Address2);
            userModel.LoginName = StringCipher.Decrypt(userModel.LoginName);
            userModel.EmailAddress = StringCipher.Decrypt(userModel.EmailAddress);
            userModel.PhoneNumber = StringCipher.Decrypt(userModel.PhoneNumber);
            userModel.MobileNumber = StringCipher.Decrypt(userModel.MobileNumber);
            userModel.FaxNumber = StringCipher.Decrypt(userModel.FaxNumber);
            userModel.PostCode = StringCipher.Decrypt(userModel.PostCode);
            return View(userModel);
        }
        [HttpPost]
        public ActionResult Profile(UserViewModel model, HttpPostedFileBase ProfilePic)
        {
            _loginService.UpdateProfile(model, ProfilePic, base.loginUserModel.LoginId);
            return View(model);
        }
        public ActionResult Index()
        {
            string[] arr = new string[2] { "Manage Organizations", "Manage Clinics" };

            DashboardViewModel model = new DashboardViewModel();
            var moduleList = _permissioninmoduleService.GetPermissionInModuleByUserId(base.loginUserModel.LoginId).ToList();
            var listDistinct = moduleList.GroupBy(i => i.ModuleId, (key, group) => group.First()).ToList().Where(t => !arr.Contains(t.Modules.ModuleName));
            model.ModuleList = listDistinct.ToList();
            //var ClinicId = _clinicService.GetClinicByLoginId(base.loginUserModel.LoginId).ClinicId;
            var DoctorCount = _doctorService.DoctorOfClinicCount(base.loginUserModel.ClinicId);
            model.DoctorCount = DoctorCount;
            model.PatientCount = _doctorService.PatientOfClinicCount(base.loginUserModel.ClinicId);
            
            return View(model);
        }

        [HttpGet]
        public ActionResult PasswordChange()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult PasswordChange(ChangePasswordViewModel Cmodel)
        {
            if (ModelState.IsValid)
            {
                var loginid = _userService.Find(base.loginUserModel.LoginId);
                var oldpassword = _userService.Find(loginid.LoginName, Cmodel.OldPassword);
                if (oldpassword == null)
                {
                    ModelState.AddModelError("OldPassword", "Current Password Does not Exsit");
                    return View(Cmodel);
                }
                ChangePassword(Cmodel);
                ModelState.AddModelError("Done", "Password Change Successfully..!!!");
            }

            return View(Cmodel);
        }
    }
}

Areas/Organizations/Views/Dashboard/PasswordChange.cshtml
@model MyOnlineClinic.Web.Models.ChangePasswordViewModel
@{
    ViewBag.Title = "PasswordChange";
    Layout = "~/Areas/Organizations/Views/Shared/_OrganizationLayout.cshtml";
}
<section class="content-header staff">
    <h1 class="underline19">
        Change Password
    </h1>
</section>

@using (Html.BeginForm("PasswordChange", "DashBoard", FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
{

    <div class="row">
        <div class="col-md-12">
            <div class="col-md-7 first_layer">
                <div class="form-horizontal" id="style-3">
                    <div class="box-body">
                        <div class="form-group role" style="margin-top:-3px;">
                            <label for="inputEmail3" class="col-sm-4 control-label">Current Password:</label>
                            <div class="col-sm-6">
                                @Html.TextBoxFor(x => x.OldPassword, new { @class = "form-control col-md-7 col-xs-12", name = "OldPassword", placeholder = "Please Enter Your Old Password", required = "required", type = "password" })
                                <div style="color:red">
                                    @Html.ValidationMessage("OldPassword")

                                </div>
                            </div>
                        </div>
                        <div class="form-group role" style="margin-top:-3px;">
                            <label for="inputEmail3" class="col-sm-4 control-label">Password:</label>
                            <div class="col-sm-6">
                                @Html.TextBoxFor(x => x.Password, new { @class = "form-control col-md-7 col-xs-12", name = "Password", placeholder = "Please Enter Your Password", required = "required", type = "password" })
                                <div style="color:red">
                                    @Html.ValidationMessageFor(m => m.Password)
                                </div>
                            </div>
                        </div>
                        <div class="form-group role" style="margin-top:-3px;">
                            <label for="inputEmail3" class="col-sm-4 control-label">Retype Password:</label>
                            <div class="col-sm-6">
                                @Html.TextBoxFor(x => x.ConfirmPassword, new { @class = "form-control col-md-7 col-xs-12", name = "RetypePassword", placeholder = "Please Retype Your Password", required = "required", type = "password" })

                                <div style="color:red">
                                    @Html.ValidationMessageFor(m => m.ConfirmPassword)
                                </div>
                            </div>
                        </div>
                        <div style="color:red;margin-left:26%;">
                            @Html.ValidationMessage("Done")
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3" style="text-align:center;">
                                <button type="button" id="btnCancel" class="btn btn-primary">Cancel</button>
                                <button id="send" type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="/AdminAssets/js/validator/validator.js"></script>
<script>
    $('#btnCancel').click(function () {
        window.location = "/Organizations/DashBoard";
    })

    // validate a field on "blur" event, a 'select' on 'change' event & a '.reuired' classed multifield on 'keyup':
    $('form')
        .on('blur', 'input[required], input.optional, select.required', validator.checkField)
        .on('change', 'select.required', validator.checkField)
        .on('keypress', 'input[required][pattern]', validator.keypress);

    $('.multi.required')
        .on('keyup blur', 'input', function () {
            validator.checkField.apply($(this).siblings().last()[0]);
        });

    // bind the validation to the form submit event
    //$('#send').click('submit');//.prop('disabled', true);

    $('form').submit(function (e) {
        e.preventDefault();
        var submit = true;
        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
            submit = false;
        }

        if (submit)
            this.submit();
        return false;
    });

    /* FOR DEMO ONLY */

</script>

Areas/Organizations/Views/Dashboard/Profile.cshtml
@model MyOnlineClinic.Web.Models.UserViewModel
@using JQueryUIHelpers;
@{
    ViewBag.Title = "Profile";
    Layout = "~/Areas/Organizations/Views/Shared/_OrganizationLayout.cshtml";
}
<style>
    table.table.table-user-information {
        color: #fff !important;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
        border-top: 1px solid #f4f4f4 !important;
    }

    img.img-circle.img-responsive {
        margin: 0px auto;
        width: 120px;
        height: 120px;
    }
</style>
<section class="content-header" style="margin-top:45px;">
    <h1 class="underline68">
        Personal Details
    </h1>
</section>
                        @using (Html.BeginForm("Profile", "Dashboard", FormMethod.Post, new { @class = "form-horizontal form-label-left", enctype = "multipart/form-data" }))
                        {
                            @Html.HiddenFor(m => m.MemberId)
                            @Html.HiddenFor(m => m.LoginId)
                            @Html.HiddenFor(m => m.ProfilePic)
                            @Html.HiddenFor(m => m.LoginName)
                            @Html.HiddenFor(m => m.EmailAddress)
                       <div class="container-fulid">
    <div class="row profile">
        <div class="col-md-2 col-md-offset-5">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <img src="@Model.ProfilePic" class="img-responsive img-circle" alt="">
                </div>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        @Model.FirstName
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="col-md-12">
    <div class="col-md-12 fifteen_layer" style="margin-top:10px;">
        <div class="panel-body">
            <div class="row">
                <div class=" col-md-5 col-md-offset-3 ">
                    <table class="table table-user-information" style="margin-left:40px;">
                        <tbody>

                            <tr>
                                <td>User Name:</td>
                                <td>@Model.LoginName</td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td>@Model.EmailAddress</td>
                            </tr>

                           
                            <tr>
                                <td>Phone No.:</td>
                                <td>@Model.PhoneNumber</td>
                            </tr>
                            <tr>
                                <td>Mobile No.:</td>
                                <td>@Model.MobileNumber</td>
                            </tr>
                            <tr>
                                <td>Fax Number:</td>
                                <td>@Model.FaxNumber</td>
                            </tr>
                            <tr>
                                <td>Post Code:</td>
                                <td>@Model.PostCode</td>
                            </tr>
                            <tr>
                                <td>Date of birth:</td>
                                <td>
                                    @Model.DOB
                                </td>
                            </tr>
                            <tr>
                                <td>Address 1:</td>
                                <td>
                                    @Model.Address1
                                </td>
                            </tr>
                            <tr>
                                <td>Address 2:</td>
                                <td>
                                    @Model.Address2
                                </td>
                            </tr>
                            <tr>
                                <td>Profile Pic:</td>
                                <td>
                                    <img src="@Model.ProfilePic" id="imgProfile" height="25" width="25" />
                                    <input type="file" name="ProfilePic" id="ProfilePic" onchange="ShowPreview(this)" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>

<div class="row">
    <div class="col-md-12" style="margin-top:20px; margin-bottom:20px;">
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3" style="text-align:center;">
                <button type="submit" id="btnCancel" class="btn btn-success">Cancel</button>
                <button type="submit" id="send" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>
</div>

  }
                   

<script src="/AdminAssets/js/validator/validator.js"></script>
<script>
    $('#btnCancel').click(function () {
        window.location = "/Organizations/dashboard";
    })

    $(document).ready(function () {
        
        // initialize the validator function
        validator.message['date'] = 'not a real date';

        // validate a field on "blur" event, a 'select' on 'change' event & a '.reuired' classed multifield on 'keyup':
        $('form')
            .on('blur', 'input[required], input.optional, select.required', validator.checkField)
            .on('change', 'select.required', validator.checkField)
            .on('keypress', 'input[required][pattern]', validator.keypress);

        $('.multi.required')
            .on('keyup blur', 'input', function () {
                validator.checkField.apply($(this).siblings().last()[0]);
            });

        // bind the validation to the form submit event
        //$('#send').click('submit');//.prop('disabled', true);

        $('form').submit(function (e) {
            e.preventDefault();
            var submit = true;
            // evaluate the form using generic validaing
            if (!validator.checkAll($(this))) {
                submit = false;
            }

            if (submit)
                this.submit();
            return false;
        });

        /* FOR DEMO ONLY */
        $('#vfields').change(function () {
            $('form').toggleClass('mode2');
        }).prop('checked', false);

        $('#alerts').change(function () {
            validator.defaults.alerts = (this.checked) ? false : true;
            if (this.checked)
                $('form .alert').remove();
        }).prop('checked', false)
    });
</script>